### PR TITLE
upgrade clj-kondo to 2022.09.08

### PR DESCRIPTION
**Pull request by avelino**
refs:
- https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md#20220908
- https://github.com/clj-kondo/clj-kondo/releases/tag/v2022.09.08

### CODE REVIEW

**Comment by avelino** [comment]
cc @puredanger

**Comment by puredanger** [comment]
Hi, this project does not take PRs, but I will update it the next time I do dep bumps.

**Comment by avelino** [comment]
> Hi, this project does not take PRs, but I will update it the next time I do dep bumps.

can you explain why this project does not accept public contribution (or send me the link where it talks about this)?

**Comment by puredanger** [comment]
The Clojure contrib projects follow the contribution guidelines of Clojure itself. We do accept contributions via patches in the jira system. To file issues, we ask that you create a question at https://ask.clojure.org with tag `request` or `problem` - we will create a linked jira issue from that. If you wish to provide a patch, you can become a contributor, gain access to jira, and provide a patch that way. See link below for more info.

https://clojure.org/dev/dev

In this particular case, I don't think it's worth the effort as I just periodically review and update all the versions in this project so I'll catch it at some point in the next couple months.

**Comment by avelino** [comment]
@puredanger  https://clojure.atlassian.net/servicedesk/customer/portal/1/SUPPORT-113?created=true

**Pull request closed without merging**
